// ng-cli-with-cmpts/src/app/location-job.component.ts
import { Component, Input } from '@angular/core';
import { Job } from './interfaces';
import { DatesService } from './dates.service';

@Component({
  selector: 'location-job',
  template: `<div>
    <span>{{ job.name }}</span>
    <date-cell *ngFor="let date of dates;" [date]="date"></date-cell>
</div>`
})
export class LocationJobComponent {
  @Input()
  job: Job;

  dates: Date[];

  constructor(private ds: DatesService) {}

  ngOnInit() {
    this.dates = this.ds.dates;
  }
}

// react-webpack/src/components/LocationJobComponent.tsx
import * as React from 'react';
import { DateCellComponent } from './DateCellComponent';
import { Job } from './interfaces';


export function LocationJobComponent(props: {job: Job, dates: Date[]}) {
  const datesList = props.dates.map((date: Date) => <DateCellComponent date={ date } />);

  return (
    <div>
      <span>{ props.job.name }</span>
      { datesList }
    </div>
  )
}
