// ng-cli-with-cmpts/src/app/location-group.component.ts
import { Component, Input } from '@angular/core';
import { LocationGroup } from './interfaces';

@Component({
  selector: 'location-group',
  template: `<div>{{ locationGroup?.name }}</div> 
<location *ngFor="let location of locationGroup.locations" [location]="location"></location>`
})
export class LocationGroupComponent {
  @Input()
  locationGroup: LocationGroup;
}

// react-webpack/src/components/LocationGroupComponent.tsx
import * as React from 'react';
import { LocationComponent } from './LocationComponent';
import { LocationGroup, Location } from './interfaces';

export function LocationGroupComponent(props: {group: LocationGroup, dates: Date[]}) {
  const locationsList = props.group.locations.map((location: Location) => <LocationComponent location={ location } dates={ props.dates } />);

  return <div>
    <div>{ props.group.name }</div>
    { locationsList }
  </div>;
}
