// react-webpack/src/components/LocationComponent.tsx
import * as React from 'react';
import { LocationJobComponent } from './LocationJobComponent';
import { Location, Job } from './interfaces';


export function LocationComponent(props: {location: Location, dates: Date[]}) {
  const jobsList = props.location.jobs.map((job: Job) => <LocationJobComponent job={ job } dates={ props.dates } />);

  return (
    <div>
      <div>{ props.location.name }</div>
      { jobsList }
    </div>
  );
}

// ng-cli-with-cmpts/src/app/location.component.ts
import { Component, Input } from '@angular/core';
import { Location } from './interfaces';

@Component({
  selector: 'location',
  template: `
<div>{{ location?.name }}</div> 
<location-job *ngFor="let job of location.jobs" [job]="job"></location-job>
`,
})
export class LocationComponent {
  @Input()
  location: Location;
}
